steps:
  - name: 'gradle:6.0.0-jdk11'
    entrypoint: 'gradle'
    args: ['build', 'codeCoverageReport', 'publishCodeCovReport', 'appengineDeploy', '-PgoogleProjectId=lims-acoleman-sb']
    env:
      - 'CODECOV_TOKEN="59ff356b-47cb-4fbe-a60a-5dc4bcb1a223"'